[ 2025-08-08 16:43:52,405 ] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.5:5000
[ 2025-08-08 16:43:52,407 ] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2025-08-08 16:43:52,436 ] 97 werkzeug - INFO - 127.0.0.1 - - [08/Aug/2025 16:43:52] "GET /predictdata HTTP/1.1" 200 -
[ 2025-08-08 16:44:16,392 ] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DS-Project\Student-Performance-Indicator\app.py", line 40, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py] line number [13] error message[name 'os' is not defined]
[ 2025-08-08 16:44:16,406 ] 97 werkzeug - INFO - 127.0.0.1 - - [08/Aug/2025 16:44:16] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2025-08-08 16:44:41,591 ] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DS-Project\Student-Performance-Indicator\app.py", line 40, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py] line number [13] error message[name 'os' is not defined]
[ 2025-08-08 16:44:41,595 ] 97 werkzeug - INFO - 127.0.0.1 - - [08/Aug/2025 16:44:41] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2025-08-08 16:44:45,321 ] 97 werkzeug - INFO - 127.0.0.1 - - [08/Aug/2025 16:44:45] "GET /predictdata HTTP/1.1" 200 -
[ 2025-08-08 16:45:05,070 ] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DS-Project\Student-Performance-Indicator\app.py", line 40, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py] line number [13] error message[name 'os' is not defined]
[ 2025-08-08 16:45:05,080 ] 97 werkzeug - INFO - 127.0.0.1 - - [08/Aug/2025 16:45:05] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
